=== nomisabi/XMLProject/xml/data/xsd/korisnici.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" targetNamespace="http://www.ftn.uns.ac.rs/korisnici"
	xmlns="http://www.ftn.uns.ac.rs/korisnici">

	<xs:element name="korisnik">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ime" type="xs:string" />
				<xs:element name="prezime" type="xs:string" />
				<xs:element name="korisnicko_ime" type="xs:string" />
				<xs:element name="lozinka" type="xs:string" />
				<xs:element name="email" minOccurs="1" type="xs:string" />
				<xs:element name="uloga">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="AUTOR" />
							<xs:enumeration value="RECENZENT" />
							<xs:enumeration value="UREDNIK" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="Id" type="xs:ID" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="korisnici">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="korisnik" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nomisabi/XMLProject/xml/data/xml/korisnici.xml
<?xml version="1.0" encoding="UTF-8"?>
<ko:korisnici xmlns:ko="http://www.ftn.uns.ac.rs/korisnici"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ftn.uns.ac.rs/korisnici ../xsd/korisnici.xsd">
	<ko:korisnik Id="ID001">
		<ko:ime>Petar</ko:ime>
		<ko:prezime>Petrovic</ko:prezime>
		<ko:korisnicko_ime>pero</ko:korisnicko_ime>
		<ko:lozinka>pero</ko:lozinka>
		<ko:email>WVyolNVCr9.R01w9x</ko:email>
		<ko:uloga>UREDNIK</ko:uloga>
	</ko:korisnik>
	<ko:korisnik Id="ID002">
		<ko:ime>Milan</ko:ime>
		<ko:prezime>Milanovic</ko:prezime>
		<ko:korisnicko_ime>mile</ko:korisnicko_ime>
		<ko:lozinka>mile</ko:lozinka>
		<ko:email>f</ko:email>
		<ko:uloga>RECENZENT</ko:uloga>
	</ko:korisnik>
	<ko:korisnik Id="ID003">
		<ko:ime>Uros</ko:ime>
		<ko:prezime>Urosevic</ko:prezime>
		<ko:korisnicko_ime>uros</ko:korisnicko_ime>
		<ko:lozinka>uros</ko:lozinka>
		<ko:email>XQuMZcEWFeJPWyo0Jp1rDv</ko:email>
		<ko:uloga>AUTOR</ko:uloga>
	</ko:korisnik>
	<ko:korisnik Id="ID004">
		<ko:ime>Ivana</ko:ime>
		<ko:prezime>Ivanovic</ko:prezime>
		<ko:korisnicko_ime>iva</ko:korisnicko_ime>
		<ko:lozinka>iva</ko:lozinka>
		<ko:email>PKTrhvbR9EQEGWEgTg_</ko:email>
		<ko:uloga>RECENZENT</ko:uloga>
	</ko:korisnik>
	
</ko:korisnici>
